[theme]
base = "light"
primaryColor = "#440154"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f6f6f9"
textColor = "#1a1a1a"
font = "serif"

[server]
maxUploadSize = 50

[browser]
gatherUsageStats = false
